Use caporalJS
mukkachaitanya/fr_team_eval pull request #1
Opened 2017-08-06 08:58 UTC by ArifAhmed1995

@mukkachaitanya Review please.

2017-08-06 09:32 UTC, mukkachaitanya commented
@ArifAhmed1995 I don't see you have updated the `package.json` file with the new dependency, `caporal`. I would suggest you to do so.

2017-08-06 10:49 UTC, ArifAhmed1995 commented
@mukkachaitanya Done. Also do change the `description` and `name` to whatever suits best.

2017-08-06 11:58 UTC, mukkachaitanya commented
@ArifAhmed1995 can you rebase with master to pull the latest change.

2017-08-06 12:14 UTC, mukkachaitanya requested changes

2017-08-06 12:14 UTC, mukkachaitanya commented on index.js
> +        if(Object.keys(args).length != 2){
Can you expose this functionality via a different file, say `main.js` and then separate caporal and the functionality itself.

2017-08-06 12:23 UTC, mukkachaitanya requested changes

2017-08-06 12:23 UTC, mukkachaitanya commented on index.js
> +        const promiseMarks = input.csvContents(args.teamcsv);
Also the files are reversed here. Change: 
```
const promiseMarks = input.csvContents(args.scorescsv)
const promiseTeam = input.csvContents(args.teamcsv);
```

2017-08-06 12:24 UTC, mukkachaitanya commented
@ArifAhmed1995 Also once you implement modularity. Could you write a test for the same?

2017-08-07 10:37 UTC, ArifAhmed1995 commented
I guess for the test we can have an optional argument for the `computeTeamResults` function. If that value is undefined then final result is written to current directory, otherwise is written to the filepath passed. For the test that value would refer to a `tempFile` which will be discarded after test(as already done in the test for `output`).

2017-08-07 17:18 UTC, mukkachaitanya approved these changes

2017-08-07 17:19 UTC, mukkachaitanya commented
Everything looks fine here. Merging.

2017-08-07 17:25 UTC, merged